name: Purge jsDelivr Cache

on:
  push:
    paths:
      - 'sehk-smart-recommender.json'
      - 'sehk-ui-hack.json'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/sehk-smart-recommender.json
            https://cdn.jsdelivr.net/gh/${{ github.repository }}@main/sehk-ui-hack.json
